# Generated by Django 6.0 on 2026-01-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('seccion', models.CharField(choices=[('PERFIL', 'Top Left - Sobre Mí (Perfil)'), ('EXPERIENCIA', 'Top Right - Proyectos Reales'), ('CONTACTO', 'Bottom Left - Datos de Contacto'), ('SHOWCASE', 'Bottom Right - Lo que puedo hacer')], max_length=20)),
                ('tipo_demo', models.CharField(choices=[('NINGUNO', 'Estándar (Texto/Imagen)'), ('NETFLIX', 'Vista estilo Netflix'), ('ECOMMERCE', 'Vista estilo Tienda'), ('IA_RETINA', 'Vista estilo IA/Seguridad')], default='NINGUNO', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('link_externo', models.URLField(blank=True, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
